default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  connect_timeout: <%= ENV.fetch("DB_CONNECT_TIMEOUT") { 5 } %>

development:
  <<: *default
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  database: <%= ENV.fetch("DB_NAME") { "swrails_development" } %>
  username: <%= ENV.fetch("DB_USER") { "swrails" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>

test:
  <<: *default
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  database: swrails_test
  username: <%= ENV.fetch("DB_USER") { "swrails" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
